config/routes.rb
Rails.application.routes.draw do

devise_for :users
mount Ckeditor::Engine => '/ckeditor'
get 'setting/course_batch'
get 'general_settings/all'
get 'general_settings/none'
get 'courses/:id/grouped_batches',to: 'courses#grouped_batches',as: 'courses_grouped_batches'
post 'courses/create_batch_group'
get 'courses/edit_batch_group'
patch 'courses/update_batch_group'
delete 'courses/delete_batch_group'
get 'courses/:id/assign_all',to: 'courses#assign_all',as: 'courses_assign_all'
get 'courses/:id/remove_all',to: 'courses#remove_all',as: 'courses_remove_all'
get 'batches/:id/display', to: 'batches#display', as: 'batches_display'
get 'batches/select' 
get 'batches/assign_tutor'
post 'batches/assign_tutorial'
post 'batches/:batch_id/assign_employee/',to:'batches#assign_employee',as:'batches_assign_employee'
delete 'batches/:batch_id/remove_employee/',to:'batches#remove_employee',as:'batches_remove_employee'
get 'grading_levels/select'
get 'batch_transfers/select'
get 'batch_transfers/assign_all'
get 'batch_transfers/remove_all'
get 'batch_transfers/student_transfer'
get 'batch_transfers/former_student'
get 'batch_transfers/:batch_id/graduation',to: 'batch_transfers#graduation', as: 'batch_transfers_graduation'
get 'batch_transfers/:batch_id/transfer',to: 'batch_transfers#transfer', as: 'batch_transfers_transfer'
get 'subjects/select'
get 'batches/:batch_id/subjects/subject',to: 'subjects#subject', as: 'batches_subjects_subject'
get 'elective_groups/:elective_group_id/elective_subject',to: 'elective_groups#elective_subject', as: 'elective_groups_elective_subject'
get 'students/search' 
get 'students/search_ajax'
get 'students/view_all'
get 'students/select'  
get 'students/:id/profile',to: 'students#profile',as: 'students_profile'
get 'students/:id/student_profile',to: 'students#student_profile',as: 'students_student_profile'
get 'students/:id/archived_student_profile',to: 'students#archived_student_profile',as: 'students_archived_student_profile'
get 'students/:id/generate_tc',to: 'students#generate_tc',as: 'students_generate_tc'
get 'students/archived_profile'  
get 'students/advanced_search'
get 'students/advanced_student_search'
post 'students/advanced_search_result'
get 'students/:subject_id/elective',to: 'students#elective',as: 'students_elective'
get 'home/dashboard'
get 'students/admission1'
get 'students/admission2'
post 'students/adm_create'
post 'students/archived_student_create'
get 'students/admission2_1'
get 'newscasts/select'
get 'newscasts/display'
get 'students/admission3'
get 'students/edit_immediate_contact'
patch 'students/update_immediate_contact'
patch 'students/update_immediatecontact'
get 'students/previous_data'
post 'students/previous_data_create'
get 'students/previous_subject'
post 'students/previous_subject_create'
get 'students/report'
get 'students/recent_exam_report'
get 'students/student_exam_report'
get 'students/subject_wise_report'
get 'students/academic_report'
get 'students/final_report'
get 'students/student_final_report'
get 'students/transcript_report'
get 'students/student_transcript_report'
get 'students/archived_student_transcript_report'
get 'students/archived_report'
get 'students/attendance_report'
get 'students/genrate_report'
get 'students/email'
post 'students/send_email'
get 'students/report_email'
post 'students/send_report_email'
get 'students/change_to_former'
get 'students/delete'
get 'students/remove'
get 'students/dispguardian'
get 'students/archived_student_guardian'
get 'students/addguardian'
post 'students/assign_elective'
get 'students/:subject_id/assign_all',to: 'students#assign_all',as: 'students_assign_all'
get 'students/:subject_id/remove_all',to: 'students#remove_all',as: 'students_remove_all'
get 'students/batch_details'
post 'guardians/addguardian_create',to: 'guardians#addguardian_create',as: 'guardians_addguardian_create'
get 'users/search'
get 'users/select'
get 'users/view_all'
get 'users/view_all_details'
patch 'users/:id/update_password',to:'users#update_password',as:'users_update_password'
get 'users/:id/change_password',to: 'users#change_password',as: 'users_change_password'
get 'class_timings/select'
get 'events/show'
get 'events/showdep'
get 'weekdays/select'
get 'weekdays/index'
post'weekdays/create'
get 'time_tables/select'
get 'time_tables/sub'
get 'time_tables/new'
get 'time_tables/timetable'
get 'time_table_entries/select'
get 'time_table_entries/select_subject'
get 'time_tables/work_allotment'
post'time_tables/work_allotment'
get 'time_tables/new_timetable'
post'time_table_entries/create_time'
post'time_table_entries/assign_time'
get 'exam_reports/report_center'
get 'exam_reports/exam_wise_report'
get 'exam_reports/subject_wise_report'
get 'exam_reports/generate_exam_report'
get 'exam_reports/select_batch'
get 'exam_reports/choose_batch'
get 'exam_reports/generate_subject_report'
get 'exam_reports/grouped_exam_report'
get 'exam_reports/generate_grouped_report'
get 'exam_reports/:exam_group_id/student_exam_report/:student_id',
                    to: 'exam_reports#student_exam_report',as: 'exam_reports_student_exam_report'
get 'exam_reports/:batch_id/student_report/:student_id',
                    to: 'exam_reports#student_report',as: 'exam_reports_student_report'
get 'exam_reports/:exam_group_id/consolidated_report',to: 'exam_reports#consolidated_report',as: 'exam_reports_consolidated_report'
get 'exam_reports/:batch_id/consolidated_archived_report',
                    to: 'exam_reports#consolidated_archived_report',as: 'exam_reports_consolidated_archived_report'
get 'exam_reports/archived_student_report'
get 'exam_reports/select_course'
get 'exam_reports/generate_archived_report'
get 'exam_reports/exam_group_wise_report'
get 'exam_reports/student_ranking_per_subject'
get 'exam_reports/rank_report_batch'
get 'exam_reports/generate_ranking_report'
get 'exam_reports/student_ranking_per_batch'
get 'exam_reports/generate_student_ranking_report'
get 'exam_reports/student_ranking_per_course'
get 'exam_reports/generate_student_ranking_report2'
get 'exam_reports/student_ranking_per_school'
get 'exam_reports/student_ranking_per_attendance'
get 'exam_reports/generate_student_ranking_report3'
get 'exam_reports/view_transcripts'
get 'exam_reports/generate_view_transcripts'
get 'exam_reports/:student_id/archived_student/',to: 'exam_reports#archived_student',as: 'exam_reports_archived_student'
get 'exam_reports/:student_id/student_view_transcripts/',to: 'exam_reports#student_view_transcripts',as: 'exam_reports_student_view_transcripts'
get 'exam_reports/ranking_level_report'
get 'exam_reports/select_mode'
get 'exam_reports/select_rank'
get 'exam_reports/select_rank_mode'
get 'exam_reports/generate_ranking_level_report'
get 'exam_reports/combined_report'
get 'exam_reports/combined_details'
get 'exam_reports/all'
get 'exam_reports/none'
get 'exam_reports/all1'
get 'exam_reports/none1'
get 'exam_reports/generate_combined_report'
get 'calender/change' 
get 'calender/event_view'
get 'exam_setting/:course_id/setting',to: 'exam_setting#setting', as: 'course_class_designations'
get 'exam_setting/select'
get 'exam_setting/selectrank'
get 'exam_setting/:course_id/settingrank',to: 'exam_setting#settingrank',as: 'course_ranking_levels'
get 'exam_setting/newrank'
post 'exam_setting/createrank'
get 'exam_setting/:course_id/editRank/:id',to:'exam_setting#editRank',as:'course_ranking_level'
patch 'exam_setting/updateRank'
delete 'exam_setting/:id/destroyRank', to:'exam_setting#destroyRank', as:'exam_setting_destroyRank'
get 'exam_groups/select'
patch 'exam_groups/:id/exam_group_create',to: 'exam_groups#exam_group_create',as: 'exam_groups_exam_group_create'
get 'exam_groups/:id/exams', to:'exam_groups#exams', as:'exam_groups_exams'
get 'exam_groups/connect_exam'
get 'exam_groups/assign_all'
get 'exam_groups/remove_all'
get 'exam_groups/update_connect_exam'
get 'exam_groups/publish_exam'
get 'exam_groups/publish_result'
get 'exam_groups/previous_exam_data'
get 'exam_groups/previous_exam'
get 'exam_groups/previous_exam_group'
get 'exam_groups/previous_exam_details'
get 'exams/:id/exam_score', to:'exams#exam_score', as:'exam_exam_score'
patch 'exams/update_exam_score'
get 'online_exams/assign_all'
get 'online_exams/remove_all'
post 'online_exams/createQue'
get 'online_exams/onlineView'
get 'online_exams/select'
get 'online_exams/:online_exam_id/queAns',to: 'online_exams#queAns', as: 'online_exams_queAns'
get 'online_exams/:online_exam_id/display',to: 'online_exams#display', as: 'online_exams_display'
delete 'online_exams/:batch_id/destroy/:id',to: 'online_exams#destroy', as: 'online_exams_destroy'
get 'online_exams/editQue/:online_examque_id', to: 'online_exams#editQue', as: 'online_exams_editQue'
patch 'online_exams/updateQue/:online_examque_id',to: 'online_exams#updateQue',as: 'online_exams_updateQue'
get 'online_exams/editOption/:online_examque_id', to: 'online_exams#editOption', as: 'online_exams_editOption'
patch 'online_exams/updateOption/:online_examque_id',to: 'online_exams#updateOption',as: 'online_exams_updateOption'
get 'employees/new_category'
post 'employees/add_category'
get 'employees/:category_id/edit_category', to:'employees#edit_category', as:'employees_edit_category'
patch 'employees/:category_id/update_category', to:'employees#update_category', as:'employees_update_category'
delete 'employees/:id/destroy_category', to:'employees#destroy_category', as:'employees_destroy_category'
get 'employees/new_department'
post 'employees/add_department'
get 'employees/:department_id/edit_department', to:'employees#edit_department', as:'employees_edit_department'
patch 'employees/:department_id/update_department', to:'employees#update_department', as:'employees_update_department'
delete 'employees/:id/destroy_department', to:'employees#destroy_department', as:'employees_destroy_department'
get 'employees/new_position'
post 'employees/add_position'
get 'employees/:position_id/edit_position', to:'employees#edit_position', as:'employees_edit_position'

app/controllers/exam_setting_controller.rb
class ExamSettingController < ApplicationController
    def index
    end
  
    def new
      @courses=Course.all
    end

    def newrank
      @courses=Course.all
    end

    def setting
    	@course=Course.find(params[:course_id])
	    @class_des = ClassDesignation.new
      @class_dess=@course.class_designations.all
	    @class_des1=@course.class_designations.build
    end

    def settingrank
       @course=Course.find(params[:course_id])
       @rank_lev=RankingLevel.new
       @rank_levels=@course.ranking_levels.all
       @rank_lev1=@course.ranking_levels.build
    end

    def create
      @course=Course.find(params[:course_id])
      @class_dess=@course.class_designations.all
      @class_des1=@course.class_designations.new(params_class)
     if @class_des1.save
      flash[:class_designation_notice]="Class Designation Created Successfully"
     else 
       flash[:class_designation_notice]="Class Designation Not Created Successfully"
    end
   end
    def createrank
      @course=Course.find(params[:course_id])
      @rank_levels=@course.ranking_levels.all
      @rank_lev1=@course.ranking_levels.new(params_rank)
      if @rank_lev1.save 
<<<<<<< HEAD
       flash[:ranking_level_notice]="RankingLevel Created Successfully"
       else
          flash[:ranking_level_notice]="RankingLevel Not Created Successfully"
         # render 'newrank'
       end
=======
         flash[:ranking_level_notice]="RankingLevel Created Successfully"
      else
         flash[:ranking_level_notice]="RankingLevel not Created Successfully"
         render 'newrank'
      end
>>>>>>> fbfb561eb57e695ff70384d0d18cd06c9b73263b
    end


    def destroy
        @course=Course.find(params[:course_id])
        @class_dess=@course.class_designations.all
        @class_des1=@course.class_designations.find(params[:id])
<<<<<<< HEAD
       if @class_des1.destroy
        flash[:class_designation_notice]="Class Designation Deleted Successfully"
      else 
        flash[:class_designation_notice]="Class Designation Not Deleted Successfully"
      end
   end
=======
        @class_des1.destroy
      #    flash[:ranking_level_notice]="RankingLevel Deleted Successfully"
      #   else
      #    flash[:ranking_level_notice]="RankingLevel not Deleted Successfully"
      #   render 'newrank'
      # end

    end
>>>>>>> fbfb561eb57e695ff70384d0d18cd06c9b73263b

    def destroyRank
      
       @rank_lev1=RankingLevel.find(params[:id])
       @course=@rank_lev1.course
       @rank_levels=@course.ranking_levels.all
       if @rank_lev1.destroy
         flash[:ranking_level_notice]="RankingLevel Deleted Successfully"
       else
         flash[:ranking_level_notice]="RankingLevel not Deleted Successfully"
         render 'newrank'
      end
    end

    def edit
        @course=Course.find(params[:course_id])
        @class_des1=@course.class_designations.find(params[:id])
    end

    def update
        @course=Course.find(params[:course_id])
        @class_dess=@course.class_designations.all
         @class_des1=@course.class_designations.find(params[:id])
        if @class_des1.update(params_class)
          flash[:class_designation_notice]="Class Designation Updated Successfully"
        else 
         flash[:class_designation_notice]="Class Designation Not Updated Successfully"
        end
    end
    def editRank
        @course=Course.find(params[:course_id])
        @rank_lev1=@course.ranking_levels.find(params[:id])
    end

    def updateRank
      @course=Course.find(params[:course_id])
      @rank_levels=@course.ranking_levels.all
      @rank_lev1=@course.ranking_levels.find(params[:id])
     if @rank_lev1.update(params_rank)
       flash[:ranking_level_notice]="Ranking Level Updated Successfully"
        else 
         flash[:ranking_level_notice]="Ranking Level Designation Not Updated Successfully"
        end
    end

    def select
        @course=Course.find(params[:course][:id])
        @class_dess=@course.class_designations.all
    end

    def selectrank
        @course=Course.find(params[:course][:id])
       @rank_levels=@course.ranking_levels.all
         
    end
    
    private
    def params_class
      params.require(:class_designation).permit(:name,:marks)
    end

    private
    def params_rank
      params.require(:ranking_level).permit(:name,:marks,:marks_limit_type,:subject_limit_type,:subject_count,:full_course)
    end

end

app/helpers/exam_setting_helper.rb
module ExamSettingHelper
end

app/views/exam_setting/_editRank.html.erb
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
  <h3><%= "Editing " %></h3>
</div>
<div class="modal-body">
        <ul class="errors"></ul>
<%= form_for [@course,@rank_lev1],url:{:action=>'updateRank',course_id: @course.id,id: @rank_lev1},method: :patch,remote: true do |f|%>
<table class="table" style="width:85%">
<tr>
    <td class="col-2"><%= f.label :name , class: "control-label"%></td>
    <td><%=f.text_field :name ,:style =>"width: 250px", class: "form-control"%></td>
</tr>
        
 <tr>
    <td class="col-2"><%= f.label :marks, class: "control-label"%></td>
     <td><%=f.text_field :marks ,:style =>"width: 250px", class: "form-control"%></td>
     
  </tr>

  <tr>
     <td class="col-2"><%= f.label :marks_limit_Type , class: "control-label"%></td>
     <td><%=f.select :marks_limit_type, ["Upper", "Lower", "Exact"],:style =>"width: 250px", class: "form-control" %></td>
     
  </tr>

  <tr>
      <td class="col-2"><%= f.label :Number_Of_Subjects , class: "control-label"%></td>
      <td><%=f.text_field :subject_count ,:style =>"width: 250px", class: "form-control"%></td>
  </tr>

  <tr>
     <td class="col-2"><%= f.label :Subject_limit_Type , class: "control-label"%></td>
   <td><%=f.select :subject_limit_type, ["Upper", "Lower", "Exact"],:style =>"width: 250px", class: "form-control" %></td>
  </tr>
   <tr>

         <td class="col-2"><%= f.label :Consider_full_course_duration? , class: "control-label"%></td>
            
            <td><%= f.check_box :full_course, :checked => false %> </td>
        </tr>
   <tr>
        <td colspan="2"><%= f.submit 'Submit', class: "btn btn-primary"%>
        <%= link_to 'cancel', '#', class: "btn btn-default",data:{dismiss:"modal"}%></td>
        </tr>
    </table>
<% end %>
</div>

</div></div>

app/views/exam_setting/_formrank.html.erb
<div class="modal-body">
        <ul class="errors"></ul>
<%= form_for [@course,@rank_lev1],url:{:action=>'createrank',course_id: @course.id},method: :post,remote: true do |f|%>
<table class="table" style="width:85%">
<tr>
    <td class="col-2"><%= f.label :name , class: "control-label"%></td>
    <td><%=f.text_field :name ,:style =>"width: 250px", class: "form-control"%></td>
</tr>
        
 <tr>
    <td class="col-2"><%= f.label :marks , class: "control-label"%></td>
    <td><%=f.text_field :marks ,:style =>"width: 250px", class: "form-control"%></td>
  </tr>

  <tr>
     <td class="col-2"><%= f.label :marks_limit_Type , class: "control-label"%></td>
      
        <td><%=f.select :marks_limit_type, ["Upper", "Lower", "Exact"],:style =>"width: 250px", class: "form-control" %></td>

  </tr>

  <tr>
      <td class="col-2"><%= f.label :Number_Of_Subjects , class: "control-label"%></td>
      <td><%=f.text_field :subject_count ,:style =>"width: 250px", class: "form-control"%></td>
  </tr>

  <tr>
     <td class="col-2"><%= f.label :Subject_limit_Type , class: "control-label"%></td>
        <td><%=f.select :subject_limit_type, ["Upper", "Lower", "Exact"],:style =>"width: 250px", class: "form-control" %></td>
  
  </tr>
   <tr>

         <td class="col-2"><%= f.label :Consider_full_course_duration? , class: "control-label"%></td>
            
            <td><%= f.check_box :full_course, :checked => false %> </td>
        </tr>
   <tr>
        <td colspan="2"><%= f.submit 'Submit', class: "btn btn-primary"%>
        <%= link_to 'cancel', '#', class: "btn btn-default",data:{dismiss:"modal"}%></td>
        </tr>
    </table>
<% end %>
</div>

app/views/exam_setting/_new.html.erb
 <% @class_dess.each do |c| %>
        <tr>
            <td class="col-2"><%= c.name %></td>
               <td class="col-2"><%= c.marks %></td>

                <td><%=link_to 'Edit',edit_course_exam_setting_path(c.course,c),remote: true%></td>
                 <td><%= link_to 'Delete', course_exam_setting_path(c.course,c),remote:true,
                    method: :delete, data: { confirm: "Are you sure to delete"} %></td>
          </tr>   
            
      <% end %>

app/views/exam_setting/_newrank.html.erb
<%@rank_levels.each do |r| %>
        <tr>
            <td class="col-2"><%= r.name %></td>
                 <td><%=link_to 'Edit', course_ranking_level_path(r.course,r),remote: true%></td>
            <td><%= link_to 'Delete', exam_setting_destroyRank_path(r),remote:true,
                    method: :delete, data: { confirm: "Are you sure to delete"} %></td>
                
          </tr>   
            
      <% end %>

     

app/views/exam_setting/_rank.html.erb
<% unless flash[:ranking_level_notice].nil? %>
    <div align="center" class="alert alert-success" style="width:100%"> <%= flash[:ranking_level_notice] %> </div>
  <%end%>
<div class="add_sub",style="margin-top:200px">
 <%= link_to 'Add', course_ranking_levels_path(@course), remote:true%>
</div> 
   <table align="center" class="table table-hover" style="width:800px">
  <thead>
  	<tr class="tr-head">
        <th colspan="3">Ranking Levels</th>
     </tr>
  </thead>
  <tbody class="product-index">
      <%= render 'newrank' %>
    </tbody>

</table>

app/views/exam_setting/_setting.html.erb
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
<h3>Class Designation</h3>
</div>
<%= render "form" %>
</div></div>

app/views/exam_setting/destroy.js.erb
<%=render 'save' %>

app/views/exam_setting/destroyRank.js.erb
<%=render 'saverank' %>

app/views/exam_setting/editRank.js.erb
$('#myModalrank').html("<%= j render 'editRank'%>")
$("#myModalrank").modal('show')

app/views/exam_setting/new.html.erb
<div id="content-header">
  <h1>Class Designations</h1>
  <h3>Manage Class Designations</h3>
  <div id="app-back-button">
      <%= link_to image_tag("buttons/back.png",:border => 0), :back  %>
  </div>
<div><%= image_tag("underline.jpg",width: "100%")%></div>
</div>


<div id="page-yield">

 <div class="box">
<div class="text-input-bg">
<%= form_for :course, url:{action:'select'},method: :get,remote:true, html:{id:"class_form"} do  |f| %>
<%= f.label :select_course %>
<%= f.select :id, @courses.collect {|b| [b.course_name,b.id]}, {prompt:true},{onchange:"$('#class_form').submit();"}%>  
<%end%>
</div><br/><br/><br/>

<div id="course_div"></div>
 <div id="myModal" class="modal fade">
 </div>
</div></div>

app/views/exam_setting/newrank.html.erb
<div id="content-header">
  <h1>Ranking Levels</h1>
  <h3>Manage Ranking Levels</h3>
  <div id="app-back-button">
      <%= link_to image_tag("buttons/back.png",:border => 0), :back %>
  </div>
<div><%= image_tag("underline.jpg",width: "100%")%></div>
</div>


<div id="page-yield">


 <div class="box">
<div class="text-input-bg">
<%= form_for :course, url:{action:'selectrank'},method: :get,remote:true, html:{id:"class_form"} do  |f| %>
<%= f.label :select_course %>
<%= f.select :id, @courses.collect {|b| [b.course_name,b.id]}, {prompt:true},{onchange:"$('#class_form').submit();"}%>  
<%end%>
</div><br/><br/><br/>

<div id="course_div"></div>
 <div id="myModal" class="modal fade"></div>
<div id="rank_div"></div>
 <div id="myModalrank" class="modal fade"></div>
</div></div>

app/views/exam_setting/select.js.erb
$('#course_div').html("<%= j render 'class_designation'%>");

app/views/exam_setting/selectrank.js.erb
$('#rank_div').html("<%= j render 'rank'%>");

app/views/exam_setting/settingrank.js.erb
$('#myModalrank').html("<%= j render 'settingrank'%>")
$("#myModalrank").modal('show')