config/routes.rb
Rails.application.routes.draw do

devise_for :users
mount Ckeditor::Engine => '/ckeditor'
get 'setting/course_batch'
get 'general_settings/all'
get 'general_settings/none'
get 'courses/:id/grouped_batches',to: 'courses#grouped_batches',as: 'courses_grouped_batches'
post 'courses/create_batch_group'
get 'courses/edit_batch_group'
patch 'courses/update_batch_group'
delete 'courses/delete_batch_group'
get 'courses/:id/assign_all',to: 'courses#assign_all',as: 'courses_assign_all'
get 'courses/:id/remove_all',to: 'courses#remove_all',as: 'courses_remove_all'
get 'batches/:id/display', to: 'batches#display', as: 'batches_display'
get 'batches/select' 
get 'batches/assign_tutor'
post 'batches/assign_tutorial'
post 'batches/:batch_id/assign_employee/',to:'batches#assign_employee',as:'batches_assign_employee'
delete 'batches/:batch_id/remove_employee/',to:'batches#remove_employee',as:'batches_remove_employee'
get 'grading_levels/select'
get 'batch_transfers/select'
get 'batch_transfers/assign_all'
get 'batch_transfers/remove_all'
get 'batch_transfers/student_transfer'
get 'batch_transfers/former_student'
get 'batch_transfers/:batch_id/graduation',to: 'batch_transfers#graduation', as: 'batch_transfers_graduation'
get 'batch_transfers/:batch_id/transfer',to: 'batch_transfers#transfer', as: 'batch_transfers_transfer'
get 'subjects/select'
get 'batches/:batch_id/subjects/subject',to: 'subjects#subject', as: 'batches_subjects_subject'
get 'elective_groups/:elective_group_id/elective_subject',to: 'elective_groups#elective_subject', as: 'elective_groups_elective_subject'
get 'students/search' 
get 'students/search_ajax'
get 'students/view_all'
get 'students/select'  
get 'students/:id/profile',to: 'students#profile',as: 'students_profile'
get 'students/:id/student_profile',to: 'students#student_profile',as: 'students_student_profile'
get 'students/:id/archived_student_profile',to: 'students#archived_student_profile',as: 'students_archived_student_profile'
get 'students/:id/generate_tc',to: 'students#generate_tc',as: 'students_generate_tc'
get 'students/archived_profile'  
get 'students/advanced_search'
get 'students/advanced_student_search'
post 'students/advanced_search_result'
get 'students/:subject_id/elective',to: 'students#elective',as: 'students_elective'
get 'home/dashboard'
get 'students/admission1'
get 'students/admission2'
post 'students/adm_create'
post 'students/archived_student_create'
get 'students/admission2_1'
get 'newscasts/select'
get 'newscasts/display'
get 'students/admission3'
get 'students/edit_immediate_contact'
patch 'students/update_immediate_contact'
patch 'students/update_immediatecontact'
get 'students/previous_data'
post 'students/previous_data_create'
get 'students/previous_subject'
post 'students/previous_subject_create'
get 'students/report'
get 'students/recent_exam_report'
get 'students/student_exam_report'
get 'students/subject_wise_report'
get 'students/academic_report'
get 'students/final_report'
get 'students/student_final_report'
get 'students/transcript_report'
get 'students/student_transcript_report'
get 'students/archived_student_transcript_report'
get 'students/archived_report'
get 'students/attendance_report'
get 'students/genrate_report'
get 'students/email'
post 'students/send_email'
get 'students/report_email'
post 'students/send_report_email'
get 'students/change_to_former'
get 'students/delete'
get 'students/remove'
get 'students/dispguardian'
get 'students/archived_student_guardian'
get 'students/addguardian'
post 'students/assign_elective'
get 'students/:subject_id/assign_all',to: 'students#assign_all',as: 'students_assign_all'
get 'students/:subject_id/remove_all',to: 'students#remove_all',as: 'students_remove_all'
get 'students/batch_details'
post 'guardians/addguardian_create',to: 'guardians#addguardian_create',as: 'guardians_addguardian_create'
get 'users/search'
get 'users/select'
get 'users/view_all'
get 'users/view_all_details'
patch 'users/:id/update_password',to:'users#update_password',as:'users_update_password'
get 'users/:id/change_password',to: 'users#change_password',as: 'users_change_password'
get 'class_timings/select'
get 'events/show'
get 'events/showdep'
get 'weekdays/select'
get 'weekdays/index'
post'weekdays/create'
get 'time_tables/select'
get 'time_tables/sub'
get 'time_tables/new'
get 'time_tables/timetable'
get 'time_table_entries/select'
get 'time_table_entries/select_subject'
get 'time_tables/work_allotment'
post'time_tables/work_allotment'
get 'time_tables/new_timetable'
post'time_table_entries/create_time'
post'time_table_entries/assign_time'
get 'exam_reports/report_center'
get 'exam_reports/exam_wise_report'
get 'exam_reports/subject_wise_report'
get 'exam_reports/generate_exam_report'
get 'exam_reports/select_batch'
get 'exam_reports/choose_batch'
get 'exam_reports/generate_subject_report'
get 'exam_reports/grouped_exam_report'
get 'exam_reports/generate_grouped_report'
get 'exam_reports/:exam_group_id/student_exam_report/:student_id',
                    to: 'exam_reports#student_exam_report',as: 'exam_reports_student_exam_report'
get 'exam_reports/:batch_id/student_report/:student_id',
                    to: 'exam_reports#student_report',as: 'exam_reports_student_report'
get 'exam_reports/:exam_group_id/consolidated_report',to: 'exam_reports#consolidated_report',as: 'exam_reports_consolidated_report'
get 'exam_reports/:batch_id/consolidated_archived_report',
                    to: 'exam_reports#consolidated_archived_report',as: 'exam_reports_consolidated_archived_report'
get 'exam_reports/archived_student_report'
get 'exam_reports/select_course'
get 'exam_reports/generate_archived_report'
get 'exam_reports/exam_group_wise_report'
get 'exam_reports/student_ranking_per_subject'
get 'exam_reports/rank_report_batch'
get 'exam_reports/generate_ranking_report'
get 'exam_reports/student_ranking_per_batch'
get 'exam_reports/generate_student_ranking_report'
get 'exam_reports/student_ranking_per_course'
get 'exam_reports/generate_student_ranking_report2'
get 'exam_reports/student_ranking_per_school'
get 'exam_reports/student_ranking_per_attendance'
get 'exam_reports/generate_student_ranking_report3'
get 'exam_reports/view_transcripts'
get 'exam_reports/generate_view_transcripts'
get 'exam_reports/:student_id/archived_student/',to: 'exam_reports#archived_student',as: 'exam_reports_archived_student'
get 'exam_reports/:student_id/student_view_transcripts/',to: 'exam_reports#student_view_transcripts',as: 'exam_reports_student_view_transcripts'
get 'exam_reports/ranking_level_report'
get 'exam_reports/select_mode'
get 'exam_reports/select_rank'
get 'exam_reports/select_rank_mode'
get 'exam_reports/generate_ranking_level_report'
get 'exam_reports/combined_report'
get 'exam_reports/combined_details'
get 'exam_reports/all'
get 'exam_reports/none'
get 'exam_reports/all1'
get 'exam_reports/none1'
get 'exam_reports/generate_combined_report'
get 'calender/change' 
get 'calender/event_view'
get 'exam_setting/:course_id/setting',to: 'exam_setting#setting', as: 'course_class_designations'
get 'exam_setting/select'
get 'exam_setting/selectrank'
get 'exam_setting/:course_id/settingrank',to: 'exam_setting#settingrank',as: 'course_ranking_levels'
get 'exam_setting/newrank'
post 'exam_setting/createrank'
get 'exam_setting/:course_id/editRank/:id',to:'exam_setting#editRank',as:'course_ranking_level'
patch 'exam_setting/updateRank'
delete 'exam_setting/:id/destroyRank', to:'exam_setting#destroyRank', as:'exam_setting_destroyRank'
get 'exam_groups/select'
patch 'exam_groups/:id/exam_group_create',to: 'exam_groups#exam_group_create',as: 'exam_groups_exam_group_create'
get 'exam_groups/:id/exams', to:'exam_groups#exams', as:'exam_groups_exams'
get 'exam_groups/connect_exam'
get 'exam_groups/assign_all'
get 'exam_groups/remove_all'
get 'exam_groups/update_connect_exam'
get 'exam_groups/publish_exam'
get 'exam_groups/publish_result'
get 'exam_groups/previous_exam_data'
get 'exam_groups/previous_exam'
get 'exam_groups/previous_exam_group'
get 'exam_groups/previous_exam_details'
get 'exams/:id/exam_score', to:'exams#exam_score', as:'exam_exam_score'
patch 'exams/update_exam_score'
get 'online_exams/assign_all'
get 'online_exams/remove_all'
post 'online_exams/createQue'
get 'online_exams/onlineView'
get 'online_exams/select'
get 'online_exams/:online_exam_id/queAns',to: 'online_exams#queAns', as: 'online_exams_queAns'
get 'online_exams/:online_exam_id/display',to: 'online_exams#display', as: 'online_exams_display'
delete 'online_exams/:batch_id/destroy/:id',to: 'online_exams#destroy', as: 'online_exams_destroy'
get 'online_exams/editQue/:online_examque_id', to: 'online_exams#editQue', as: 'online_exams_editQue'
patch 'online_exams/updateQue/:online_examque_id',to: 'online_exams#updateQue',as: 'online_exams_updateQue'
get 'online_exams/editOption/:online_examque_id', to: 'online_exams#editOption', as: 'online_exams_editOption'
patch 'online_exams/updateOption/:online_examque_id',to: 'online_exams#updateOption',as: 'online_exams_updateOption'
get 'employees/new_category'
post 'employees/add_category'
get 'employees/:category_id/edit_category', to:'employees#edit_category', as:'employees_edit_category'
patch 'employees/:category_id/update_category', to:'employees#update_category', as:'employees_update_category'
delete 'employees/:id/destroy_category', to:'employees#destroy_category', as:'employees_destroy_category'
get 'employees/new_department'
post 'employees/add_department'
get 'employees/:department_id/edit_department', to:'employees#edit_department', as:'employees_edit_department'
patch 'employees/:department_id/update_department', to:'employees#update_department', as:'employees_update_department'
delete 'employees/:id/destroy_department', to:'employees#destroy_department', as:'employees_destroy_department'
get 'employees/new_position'
post 'employees/add_position'
get 'employees/:position_id/edit_position', to:'employees#edit_position', as:'employees_edit_position'

app/models/exam_group.rb
class ExamGroup < ActiveRecord::Base
	
	belongs_to :batch
	has_many :exams,dependent: :destroy
	accepts_nested_attributes_for :exams 
	validates :name , presence:true, length:{minimum:1,maximum:30},format:{ with: /\A[a-zA-Z0-9._" "-\/]+\Z/}
	validates :exam_type, presence:true
end

app/controllers/exam_groups_controller.rb
class ExamGroupsController < ApplicationController
 
   def select
    @course=Course.find(params[:course][:id])
    @batches=@course.batches.all

  end

  def new
    @batch=Batch.find(params[:format])
    @exam_group=@batch.exam_groups.build
    @course=@batch.course
  end

  def create
    @batch=Batch.find(params[:format])
    @exam_group=@batch.exam_groups.new(params_exam_group)
    @exam_group.save
    @subjects=@batch.subjects.where(no_exams:false)
    @exam_group.exams.build
  end

  def edit
    @exam_group=ExamGroup.find(params[:id])
    @batch=@exam_group.batch
  end

  def update
    @exam_group=ExamGroup.find(params[:id])
    @exam_group.update(params_exam_group)
    @batch=@exam_group.batch
    @subjects=@batch.subjects.where(no_exams:false)
    @exam_group.exams.build
  end

  def exam_group_create
    @exam_group=ExamGroup.find(params[:id])
    @exam_group.update(params_exam_group)
      if params[:no_create].present?
        params[:no_create].each do |s|
          @exam=Exam.find_by_subject_id_and_exam_group_id(s,@exam_group.id)
          unless @exam.nil?
            @exam.destroy
          end
        end      
      end
  end
  
  def show
    @batch=Batch.find(params[:id])
    @exam_groups=@batch.exam_groups.all
    @course=@batch.course
  end

  def exams
   @exam_group=ExamGroup.find(params[:id])
   @exams=@exam_group.exams.all
   @course=@exam_group.batch.course
   
  end

  def previous_exam
    @course=Course.find(params[:course][:id])
    @batches=@course.batches.all
  end

  def previous_exam_group
    @batch=Batch.find(params[:batch][:id])
    @exam_groups=@batch.exam_groups.where(result_published:true)
  end

  def previous_exam_details
    @exams=[]
    flag=false
    @exam_group=ExamGroup.find(params[:exam_group][:id])
    exams_data=@exam_group.exams.all
    
    exams_data.each do |exam|
      exam.exam_scores.each do |es|
        if es.is_failed?
        flag=true   
        end         
       end
      if flag == true
        @exams<< exam
      end
     end
  end
  
  def connect_exam
   @batch=Batch.find(params[:format])
   @exam_groups=@batch.exam_groups.all
  end

  def assign_all
   @batch=Batch.find(params[:format])
   @exam_groups=@batch.exam_groups.all
  
  end

  def remove_all
    @batch=Batch.find(params[:format])
    @exam_groups=@batch.exam_groups.all
  end 

  def update_connect_exam
    sum=0
    @batch=Batch.find(params[:format])
    exam_groups=params[:exam_groups]
    if exam_groups.present?
      params[:exam_group].each_pair do |e,w|
        sum+=w[:weightage].to_f
      end
      if sum==100 
        params[:exam_group].each_pair do |e,w|
          exam_groups.each do |eg|
              if eg==e
                exams=Exam.where(exam_group_id:eg)
                exams.each do |exam|
                  exam.update(weightage:w[:weightage])
                flash[:notice_con]="Total weightage updated successfully"
                end
              end
          end
        end
      else
        flash[:notice_connect]="Total weightage should be 100"
      end
    else
      flash[:notice_connect]="Please select exam group"
    end
    redirect_to exam_groups_connect_exam_path(@batch)  
  end

  def publish_exam
    @date=Date.today
    @exam_group=ExamGroup.find(params[:format])
    @exam_group.update(is_published:true)
    @exam_group.exams.each do |exam|
        exam.create_exam_event
    end    
    @batch=@exam_group.batch
    @exam_groups=@batch.exam_groups.all
  end

  def publish_result
    flag=false
    @exam_group=ExamGroup.find(params[:format])
    if @exam_group.is_published? 
      @exam_group.exams.each do |exam|
        if exam.end_time >= Date.today
        flag=true
        end         
      end
      
      if flag==true  
       flash[:result_error] ="Exam results cannot be published"
      else
       @exam_group.update(result_published:true)
       flash[:result]="Result published successfully"
      end
       
    else
       flash[:result_error]="Exam scheduled not published"
    end
    redirect_to exam_groups_exams_path(@exam_group)
  end

  def destroy
    @exam_group=ExamGroup.find(params[:id])
    batch=@exam_group.batch
    @exam_group.destroy
    flash[:notice] = "Exam Group deleted successfully!"
    redirect_to exam_group_path(batch)
  end

  def previous_exam_scores
    @exam=Exam.find(params[:format])
    @exam_scores=@exam.exam_scores.where(is_failed:true)

  end

  def update_exam_score
    @exam=Exam.find(params[:id])
    @exam_group=@exam.exam_group
    @batch=@exam_group.batch
    params[:exams][:exam].each_pair do |student_id, details|
        @exam_score=ExamScore.find_by_exam_id_and_student_id(@exam.id,student_id)
        @grouped_exam=GroupedExamReport.find_by_batch_id_and_student_id_and_exam_group_id_and_subject_id(@batch.id,student_id,@exam_group.id,@exam.subject_id)
        score_grade=""
        fail=false
        fail=true if details[:marks].to_f<@exam.minimum_marks.to_f
      
      unless @exam.exam_group.exam_type=="Marks"
        percentage=(details[:marks].to_f*100)/@exam.maximum_marks.to_f
        grades=@exam.exam_group.batch.grading_levels.all
        grades.each do |grade|
          if percentage>=grade.min_score
            score_grade=grade.id
          end
        end
      end
      
          if @exam_score.nil?
            ExamScore.create(exam_id:@exam.id,student_id:student_id,
              marks:details[:marks],remarks:details[:remarks],grading_level_id:score_grade,is_failed:fail)
          else
            @exam_score.update(marks:details[:marks],remarks:details[:remarks],grading_level_id:score_grade,is_failed:fail)
          end

          if @grouped_exam.nil?
            GroupedExamReport.create(batch_id:@batch.id,student_id:student_id,
              exam_group_id:@exam_group.id,subject_id:@exam.subject_id,marks:details[:marks])
          else
            @grouped_exam.update(marks:details[:marks])
          end
      end
      redirect_to exam_groups_previous_exam_scores_path(@exam.id)
  end

  private 

    def params_exam_group
      params.require(:exam_group).permit(:name,:exam_type,:exam_date,
        exams_attributes:[:subject_id,:maximum_marks,:minimum_marks,:start_time,:end_time])
    end
end
  

app/helpers/exam_groups_helper.rb
module ExamGroupsHelper
end

app/views/exam_groups/_edit.html.erb
<%= form_for @exam_group,url: {action: 'update'} ,method: :patch,remote: true do |f|%>
 <table class="table" >
        <tr>
            <td class="col-md-2"><%= f.label :name , class: "control-label"%></td>
            <td><%=f.text_field :name ,:style =>"width: 250px", class: "form-control", required: true%></td>
        </tr>
        
        <tr>
            <td class="col-md-2"><%= f.label :type , class: "control-label"%></td>
            <td class="col-2"><%= f.select :exam_type,["Marks","Grades","Marks and Grades"]%>
            </td>
        </tr>
        
        <tr>
        <td colspan="2"><%= f.submit 'Submit', class: "btn btn-primary"%></td></tr>
    </table>
<% end %>

app/views/exam_groups/_exam_group_details.html.erb
  <%= form_for :exam_group, url:{action:'previous_exam_details'},method: :get,remote:true,html:{id: "exam_group_form"}  do |f| %>
  <div class="label-field-pair">
  <%= f.label :select_exam_group %>
  <div class="text-input-bg">
  <%= f.select :id, @exam_groups.collect {|b| [b.name,b.id]}, {prompt:true},{onchange:"$('#exam_group_form').submit();"}%>
</div></div>
<% end %>
<br/><br/>
<div id="exams_details"></div>

app/views/exam_groups/all.js.erb
$('.check_box').attr('checked', true);

app/views/exam_groups/connect_exam.html.erb
<div id="content-header">
  <h1>Exam Management</h1>
  <h3>Connect Exam</h3>
  <div id="app-back-button">
 <%= link_to image_tag("buttons/back.png",:border => 0),:back %>
  </div>
  <div><%= image_tag("underline.jpg",width: "100%")%></div>  
</div>
<div id="page-yield">
<div class="box">

<% unless flash[:notice_connect].nil? %>
    <div align="center" class="alert alert-danger" style="width:100%"> <%= flash[:notice_connect] %> </div>
<% end %>
<% unless flash[:notice_con].nil? %>
    <div align="center" class="alert alert-success" style="width:100%"> <%= flash[:notice_con] %> </div>
<% end %>
<div style="width:700px">
 <%=form_for :connect_exam , url:{action:'update_connect_exam',format:@batch.id}, method: :get do |f| %>
  <div class="row">
    <div class="col-md-3">
        Select: <%= link_to  'All', exam_groups_assign_all_path(@batch),remote:true %>
        <%= link_to  'None', exam_groups_remove_all_path(@batch), remote:true %>
      
    </div>
    <div class="col-md-3"> 
     Exam Group
    
    </div>
    <div class="col-md-3">
      Weightage
    </div>
  </div >
  <div class="row">
    <div class="col-md-12">
      <div id="connect_exam  "><%= render 'exam_connect'%></div>    
    </div>
  </div>
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-3">
    <%= f.submit 'Submit', class: "btn btn-primary"%>
  </div>
  <div class="col-md-3"></div>
    
</div>
<%end%>
</div></div></div>

app/views/exam_groups/edit.js.erb
$('#form_exam').html("<%=  j render 'edit' %>");

app/views/exam_groups/exam_group_details.js.erb
$("#exams_details").html("<% j render 'exams_details' %>")

app/views/exam_groups/index.html.erb
<div id="content-header">
  <h1>Exam Management</h1>
  <h3>Create Exam</h3>
  <div id="app-back-button">
 <%= link_to image_tag("buttons/back.png",:border => 0),:back %>
  </div>
  <div><%= image_tag("underline.jpg",width: "100%")%></div>  
</div>
<div id="inner-tab-menu">
  <ul>
    <li><%= link_to 'Previous Batch Exams', exam_groups_previous_exam_data_path %> </li>
  </ul>
</div>

<div id="page-yield">
<div class="box">

<div class="text-input-bg">
	<%= form_for :course, url:{action:'select'},method: :get,remote:true,html:{id: "exam_form"}  do |f| %>
	<%= f.label :select_course %>
  <%= f.select :id, Course.all.collect {|b| [b.course_name+" "+b.section_name,b.id]}, {prompt:true},{onchange:"$('#exam_form').submit();"}%>

<% end %>

</div><br /><br /><br/>
 
 </div>
 <div id="exam_div">
  
</div>
<div id="exam_details">
  
</div></div>

app/views/exam_groups/new.html.erb
<div id="content-header">
  <h1>Exam Management</h1>
  <h3>New Exam</h3>
  <div id="app-back-button">
 <%= link_to image_tag("buttons/back.png",:border => 0), :back %>
  </div>
  <div><%= image_tag("underline.jpg",width: "100%")%></div>  
</div>
<div id="page-yield">
<div class="box">
<div id="form_exam">

<%= render 'form' %>	
</div></div></div>

app/views/exam_groups/previous_exam.js.erb
$('#batch_div').html("<%= j render 'batch_details' %>");

app/views/exam_groups/previous_exam_group.js.erb
$('#exam_div').html("<%= j render 'exam_group_details'%>");

app/views/exam_groups/previous_exam_scores.html.erb
<div id="content-header">
  <h1>Exams</h1>
  <h3>Previous Exams Scores</h3>
  <div id="app-back-button">
    <%= link_to image_tag("buttons/back.png",:border => 0),:back %>
  </div>
 <div><%= image_tag("underline.jpg",width: "100%")%></div>
</div>

<div id="page-yield">
<div class="box">   

<table class="table table-hover" style="width:700px">
  <%=form_for :exams,url:{action:'update_exam_score',id:@exam.id},method: :patch do |f| %>  
  <tr>
    <td class="col-3" colspan="3">Exam Name: <%= @exam.exam_group.name %></td>
  </tr>
        
  <tr>
    <td class="col-3" colspan="3">
    Subject Name: <%= @exam.subject.name %></td>
  </tr>
  <tr class="tr-head">
    <td class="col-2">Student name</td>
    <td >Marks</td>
    <td >Remarks</td>
    <td ><%= 'Grades' unless @exam.exam_group.exam_type=="Marks"%></td>
  </tr> 
<% @exam_scores.each do |es| %>
<tr>
<% student=es.student%>
    <% unless es.nil? %>
    
     
      <td class="col-2"><font color="red"><%= f.label "#{student.first_name+" "+student.last_name}" %></font></td>
    
<%else%>
      <td class="col-2"><%= f.label "#{student.first_name+" "+student.last_name}" %></td>
    <%end%>
    <% unless es.nil? %>
        <td><%= f.text_field "exam[#{student.id}][marks]",value:es.marks%></td>
        <td><%= f.text_field "exam[#{student.id}][remarks]",value:es.remarks%></td>
        <td><%= f.text_field "exam[#{student.id}][grades]",value:es.grading_level.name,readonly:true,style:"width:50px" unless @exam.exam_group.exam_type=="Marks"%></td>
    <%else%>
      <td><%= f.text_field "exam[#{student.id}][marks]"%></td>
      <td><%= f.text_field "exam[#{student.id}][remarks]"%></td>
      <td><%= f.text_field "exam[#{student.id}][grades]",readonly:true,style:"width:50px" unless @exam.exam_group.exam_type=="Marks"%></td>
    <%end %>   
</tr>
<% end %> 
 <tr class="tr-head"><td colspan="4">
<%= f.submit 'Submit', class: "btn btn-primary"%>
<%= link_to 'Finish',exam_groups_previous_exam_data_path, class: "btn btn-primary"%></td>
</tr>
<%end%>
</table>

</div></div>

app/views/exam_groups/publish_exam.js.erb
$("#publish_exam<%=@exam_group.id%>").html("Exam scheduled published");

app/views/exam_groups/select.js.erb
$('#exam_div').html("<%= j render 'view_courses'%>");

app/views/exam_groups/update.js.erb
$('#form_exam').html("<%=  j render '/exams/exam_form' %>")