config/routes.rb
Rails.application.routes.draw do

devise_for :users
mount Ckeditor::Engine => '/ckeditor'
get 'setting/course_batch'
get 'general_settings/all'
get 'general_settings/none'
get 'courses/:id/grouped_batches',to: 'courses#grouped_batches',as: 'courses_grouped_batches'
post 'courses/create_batch_group'
get 'courses/edit_batch_group'
patch 'courses/update_batch_group'
delete 'courses/delete_batch_group'
get 'courses/:id/assign_all',to: 'courses#assign_all',as: 'courses_assign_all'
get 'courses/:id/remove_all',to: 'courses#remove_all',as: 'courses_remove_all'
get 'batches/:id/display', to: 'batches#display', as: 'batches_display'
get 'batches/select' 
get 'batches/assign_tutor'
post 'batches/assign_tutorial'
post 'batches/:batch_id/assign_employee/',to:'batches#assign_employee',as:'batches_assign_employee'
delete 'batches/:batch_id/remove_employee/',to:'batches#remove_employee',as:'batches_remove_employee'
get 'grading_levels/select'
get 'batch_transfers/select'
get 'batch_transfers/assign_all'
get 'batch_transfers/remove_all'
get 'batch_transfers/student_transfer'
get 'batch_transfers/former_student'
get 'batch_transfers/:batch_id/graduation',to: 'batch_transfers#graduation', as: 'batch_transfers_graduation'
get 'batch_transfers/:batch_id/transfer',to: 'batch_transfers#transfer', as: 'batch_transfers_transfer'
get 'subjects/select'
get 'batches/:batch_id/subjects/subject',to: 'subjects#subject', as: 'batches_subjects_subject'
get 'elective_groups/:elective_group_id/elective_subject',to: 'elective_groups#elective_subject', as: 'elective_groups_elective_subject'
get 'students/search' 
get 'students/search_ajax'
get 'students/view_all'
get 'students/select'  
get 'students/:id/profile',to: 'students#profile',as: 'students_profile'
get 'students/:id/student_profile',to: 'students#student_profile',as: 'students_student_profile'
get 'students/:id/archived_student_profile',to: 'students#archived_student_profile',as: 'students_archived_student_profile'
get 'students/:id/generate_tc',to: 'students#generate_tc',as: 'students_generate_tc'
get 'students/archived_profile'  
get 'students/advanced_search'
get 'students/advanced_student_search'
post 'students/advanced_search_result'
get 'students/:subject_id/elective',to: 'students#elective',as: 'students_elective'
get 'home/dashboard'
get 'students/admission1'
get 'students/admission2'
post 'students/adm_create'
post 'students/archived_student_create'
get 'students/admission2_1'
get 'newscasts/select'
get 'newscasts/display'
get 'students/admission3'
get 'students/edit_immediate_contact'
patch 'students/update_immediate_contact'
patch 'students/update_immediatecontact'
get 'students/previous_data'
post 'students/previous_data_create'
get 'students/previous_subject'
post 'students/previous_subject_create'
get 'students/report'
get 'students/recent_exam_report'
get 'students/student_exam_report'
get 'students/subject_wise_report'
get 'students/academic_report'
get 'students/final_report'
get 'students/student_final_report'
get 'students/transcript_report'
get 'students/student_transcript_report'
get 'students/archived_student_transcript_report'
get 'students/archived_report'
get 'students/attendance_report'
get 'students/genrate_report'
get 'students/email'
post 'students/send_email'
get 'students/report_email'
post 'students/send_report_email'
get 'students/change_to_former'
get 'students/delete'
get 'students/remove'
get 'students/dispguardian'
get 'students/archived_student_guardian'
get 'students/addguardian'
post 'students/assign_elective'
get 'students/:subject_id/assign_all',to: 'students#assign_all',as: 'students_assign_all'
get 'students/:subject_id/remove_all',to: 'students#remove_all',as: 'students_remove_all'
get 'students/batch_details'
post 'guardians/addguardian_create',to: 'guardians#addguardian_create',as: 'guardians_addguardian_create'
get 'users/search'
get 'users/select'
get 'users/view_all'
get 'users/view_all_details'
patch 'users/:id/update_password',to:'users#update_password',as:'users_update_password'
get 'users/:id/change_password',to: 'users#change_password',as: 'users_change_password'
get 'class_timings/select'
get 'events/show'
get 'events/showdep'
get 'weekdays/select'
get 'weekdays/index'
post'weekdays/create'
get 'time_tables/select'
get 'time_tables/sub'
get 'time_tables/new'
get 'time_tables/timetable'
get 'time_table_entries/select'
get 'time_table_entries/select_subject'
get 'time_tables/work_allotment'
post'time_tables/work_allotment'
get 'time_tables/new_timetable'
post'time_table_entries/create_time'
post'time_table_entries/assign_time'
get 'exam_reports/report_center'
get 'exam_reports/exam_wise_report'
get 'exam_reports/subject_wise_report'
get 'exam_reports/generate_exam_report'
get 'exam_reports/select_batch'
get 'exam_reports/choose_batch'
get 'exam_reports/generate_subject_report'
get 'exam_reports/grouped_exam_report'
get 'exam_reports/generate_grouped_report'
get 'exam_reports/:exam_group_id/student_exam_report/:student_id',
                    to: 'exam_reports#student_exam_report',as: 'exam_reports_student_exam_report'
get 'exam_reports/:batch_id/student_report/:student_id',
                    to: 'exam_reports#student_report',as: 'exam_reports_student_report'
get 'exam_reports/:exam_group_id/consolidated_report',to: 'exam_reports#consolidated_report',as: 'exam_reports_consolidated_report'
get 'exam_reports/:batch_id/consolidated_archived_report',
                    to: 'exam_reports#consolidated_archived_report',as: 'exam_reports_consolidated_archived_report'
get 'exam_reports/archived_student_report'
get 'exam_reports/select_course'
get 'exam_reports/generate_archived_report'
get 'exam_reports/exam_group_wise_report'
get 'exam_reports/student_ranking_per_subject'
get 'exam_reports/rank_report_batch'
get 'exam_reports/generate_ranking_report'
get 'exam_reports/student_ranking_per_batch'
get 'exam_reports/generate_student_ranking_report'
get 'exam_reports/student_ranking_per_course'
get 'exam_reports/generate_student_ranking_report2'
get 'exam_reports/student_ranking_per_school'
get 'exam_reports/student_ranking_per_attendance'
get 'exam_reports/generate_student_ranking_report3'
get 'exam_reports/view_transcripts'
get 'exam_reports/generate_view_transcripts'
get 'exam_reports/:student_id/archived_student/',to: 'exam_reports#archived_student',as: 'exam_reports_archived_student'
get 'exam_reports/:student_id/student_view_transcripts/',to: 'exam_reports#student_view_transcripts',as: 'exam_reports_student_view_transcripts'
get 'exam_reports/ranking_level_report'
get 'exam_reports/select_mode'
get 'exam_reports/select_rank'
get 'exam_reports/select_rank_mode'
get 'exam_reports/generate_ranking_level_report'
get 'exam_reports/combined_report'
get 'exam_reports/combined_details'
get 'exam_reports/all'
get 'exam_reports/none'
get 'exam_reports/all1'
get 'exam_reports/none1'
get 'exam_reports/generate_combined_report'
get 'calender/change' 
get 'calender/event_view'
get 'exam_setting/:course_id/setting',to: 'exam_setting#setting', as: 'course_class_designations'
get 'exam_setting/select'
get 'exam_setting/selectrank'
get 'exam_setting/:course_id/settingrank',to: 'exam_setting#settingrank',as: 'course_ranking_levels'
get 'exam_setting/newrank'
post 'exam_setting/createrank'
get 'exam_setting/:course_id/editRank/:id',to:'exam_setting#editRank',as:'course_ranking_level'
patch 'exam_setting/updateRank'
delete 'exam_setting/:id/destroyRank', to:'exam_setting#destroyRank', as:'exam_setting_destroyRank'
get 'exam_groups/select'
patch 'exam_groups/:id/exam_group_create',to: 'exam_groups#exam_group_create',as: 'exam_groups_exam_group_create'
get 'exam_groups/:id/exams', to:'exam_groups#exams', as:'exam_groups_exams'
get 'exam_groups/connect_exam'
get 'exam_groups/assign_all'
get 'exam_groups/remove_all'
get 'exam_groups/update_connect_exam'
get 'exam_groups/publish_exam'
get 'exam_groups/publish_result'
get 'exam_groups/previous_exam_data'
get 'exam_groups/previous_exam'
get 'exam_groups/previous_exam_group'
get 'exam_groups/previous_exam_details'
get 'exams/:id/exam_score', to:'exams#exam_score', as:'exam_exam_score'
patch 'exams/update_exam_score'
get 'online_exams/assign_all'
get 'online_exams/remove_all'
post 'online_exams/createQue'
get 'online_exams/onlineView'
get 'online_exams/select'
get 'online_exams/:online_exam_id/queAns',to: 'online_exams#queAns', as: 'online_exams_queAns'
get 'online_exams/:online_exam_id/display',to: 'online_exams#display', as: 'online_exams_display'
delete 'online_exams/:batch_id/destroy/:id',to: 'online_exams#destroy', as: 'online_exams_destroy'
get 'online_exams/editQue/:online_examque_id', to: 'online_exams#editQue', as: 'online_exams_editQue'
patch 'online_exams/updateQue/:online_examque_id',to: 'online_exams#updateQue',as: 'online_exams_updateQue'
get 'online_exams/editOption/:online_examque_id', to: 'online_exams#editOption', as: 'online_exams_editOption'
patch 'online_exams/updateOption/:online_examque_id',to: 'online_exams#updateOption',as: 'online_exams_updateOption'
get 'employees/new_category'
post 'employees/add_category'
get 'employees/:category_id/edit_category', to:'employees#edit_category', as:'employees_edit_category'
patch 'employees/:category_id/update_category', to:'employees#update_category', as:'employees_update_category'
delete 'employees/:id/destroy_category', to:'employees#destroy_category', as:'employees_destroy_category'
get 'employees/new_department'
post 'employees/add_department'
get 'employees/:department_id/edit_department', to:'employees#edit_department', as:'employees_edit_department'
patch 'employees/:department_id/update_department', to:'employees#update_department', as:'employees_update_department'
delete 'employees/:id/destroy_department', to:'employees#destroy_department', as:'employees_destroy_department'
get 'employees/new_position'
post 'employees/add_position'
get 'employees/:position_id/edit_position', to:'employees#edit_position', as:'employees_edit_position'

app/models/elective_group.rb
class ElectiveGroup < ActiveRecord::Base

	belongs_to :batch
  	has_many :subjects
  	validates :name, presence: true, length:{minimum:1,maximum: 20}, format:{  with: /\A[a-zA-Z0-9#+_" "-]+\Z/}
end

app/controllers/elective_groups_controller.rb
class ElectiveGroupsController < ApplicationController

   before_action :set_elective_group, only:[:edit,:update,:destroy]

	  def new
	    @batch = Batch.find params[:batch_id]
      @elective_group=@batch.elective_groups.build
    end
  	
  	def create
  		@batch=Batch.find(params[:batch_id])
        @subjects=@batch.subjects.where(elective_group_id:nil)
        @elective_groups=@batch.elective_groups.all
  	    @elective_group=@batch.elective_groups.new(elective_group_params)
        @elective_group.save
         flash[:notice]="Elective group Created Successfully"
  	end

    def edit  
    end

    def update
      @subjects=@batch.subjects.where(elective_group_id:nil)
      @elective_groups=@batch.elective_groups.all
      @elective_group.update(elective_group_params)
     flash[:notice]="Elective group updated Successfully"
    end

    def destroy
      @subjects=@batch.subjects.where(elective_group_id:nil)
      @elective_groups=@batch.elective_groups.all
      @elective_group.destroy
      flash[:notice]="Elective group deleted Successfully"
    end
    
    def elective_subject
      @elective_group=ElectiveGroup.find(params[:elective_group_id])
      @elective_subjects=@elective_group.subjects.all
    end

  	private
     def set_elective_group
      @batch=Batch.find(params[:batch_id])
      @elective_group=@batch.elective_groups.find(params[:id])
    end
 
	  def elective_group_params
	  	params.require(:elective_group).permit(:name)
	  end
end

app/helpers/elective_groups_helper.rb
module ElectiveGroupsHelper
end

app/views/elective_groups/_edit.html.erb
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
  <h3><%= "Editing #{@elective_group.name}" %></h3>
</div>
<%= render "form" %>
</div></div>

app/views/elective_groups/_elective_group.html.erb
 <div class="add_sub">
   <%= link_to 'Add new Elective Groups',new_batch_elective_group_path(@batch),remote:true %>
   </div>
<div>
<% if @elective_groups.empty? %>
 <h4 align="center">No Record Found </h4>
   <% else %>
<table align="center" class="table table-hover" style="width:800px">
<ul id="category-list">
<thead>
  <tr class="tr-head"><th colspan="6">Elective Groups Name</th>
  </tr>
    </thead>
   <% @elective_groups.each do |elective_group| %>
  <tbody>
    <tr><td><%=link_to elective_group.name,elective_groups_elective_subject_path(elective_group)%></td>
    <td><%= link_to 'edit',edit_batch_elective_group_path(elective_group.batch,elective_group),remote:true%></td>

    <td><%= link_to 'delete', [elective_group.batch,elective_group], remote:true,
        method: :delete, data:{confirm:"Are you sure to delete elective group: #{elective_group.name}?"} %></td>
    <td><%=link_to 'Add Elective Subject',elective_groups_elective_subject_path(elective_group) %></td>
    </tr>
</tbody>
<% end %>
</table>
<%end%>
</div>
</div>
</div>

app/views/elective_groups/_form.html.erb
<div class="modal-body">
	<ul class="errors"></ul>
<%= form_for ([@batch, @elective_group]),remote: true do |f|%>
<table class="table" style="width:85%">
        <tr>
            <td class="col-2"><%= f.label :name , class: "control-label"%></td>
            <td><%=f.text_field :name ,:style =>"width: 250px", class: "form-control"%></td>
        </tr>
		<tr>      
	        <td colspan="2"><%= f.submit 'Submit', class: "btn btn-primary"%>
	        <%= link_to 'cancel', '#', class: "btn btn-default",data:{dismiss:"modal"}%></td>
	    </tr>
    </table>
<% end %>
</div>

app/views/elective_groups/_new.html.erb
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
<h3>Add New Elective Group</h3>
</div>
<%= render "form" %>
</div></div>

app/views/elective_groups/_save.js.erb
$("ul.errors").html("")
<% if @elective_group.errors.any? %>
		<% @elective_group.errors.full_messages.each do |message| %>
		$("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
		<% end %>
<% else %>
  $("#myModal").modal("hide")
  $('#subject_div').html("<%= j render 'subjects/subject'%>");
<% end %>

app/views/elective_groups/_view_elective_subjects.html.erb
<% if @elective_subjects.present? %>
<% if @elective_subjects.empty? %>
 <h4 align="center">No Record Found </h4>
   <% else %>
<table align="center" class="table table-hover" style="width:800px">
<ul id="category-list">
<thead>
  <tr class="tr-head"><th colspan="5">Elective Subject</th>
  </tr>
    </thead>
   <% @elective_subjects.each do |subject| %>
   <tbody>
    <tr><td><%= subject.name %></td>
        <td><%= subject.code %></td>
        <td><%= link_to 'edit',edit_batch_elective_group_subject_path(@elective_group.batch,
            @elective_group,subject),remote:true %></td>
        <td><%= link_to 'delete',[@elective_group.batch,@elective_group,subject],remote:true,
        method: :delete, data:{confirm:"Are you sure to delete elective subject: #{subject.name}?"} %></td>
         <td><%= link_to 'Assign Students',students_elective_path(subject) %></td>
    </tr>
    </tbody>
<% end %>
</table>
<%end%>
<% end %>

app/views/elective_groups/create.js.erb
<%= render "save" %>

app/views/elective_groups/destroy.js.erb
<%= render "save" %>

app/views/elective_groups/edit.js.erb
$('#myModal').html("<%= j render 'edit'%>")
$("#myModal").modal('show')

app/views/elective_groups/elective_subject.html.erb
<div id="content-header">
  <h1>Elective Subjects</h1>
  <h3>Home</h3>
  <div id="app-back-button">
    <%= link_to image_tag("buttons/back.png",:border => 0), :back  %>
  </div>
 <div><%= image_tag("underline.jpg",width: "100%")%></div>
</div>

<div id="page-yield">
 <div class="box">
    <div class="bread_crumb">
    <%= link_to "Batch "+@elective_group.batch.name, batches_display_path(@elective_group.batch) %> &raquo;
     <%= link_to "Elective Group "+@elective_group.name,batches_subjects_subject_path(@elective_group.batch) %> &raquo;Elective Subjects
    </div><br/>
<div class="add_sub",style="margin-top:20px">
     <%= link_to 'Add Elective Subjects',new_batch_elective_group_subject_path(@elective_group.batch,
                @elective_group),remote:true%>
  </div>
<div id="elective_div">
<%= render 'view_elective_subjects' %>
</div>
 <div id="myModal" class="modal fade">
 </div> </div></div>

app/views/elective_groups/new.js.erb
$('#myModal').html("<%= j render 'new'%>")
$("#myModal").modal('show')

app/views/elective_groups/update.js.erb
<%= render "save" %>